export const BASE_URL: string = "http://baobab.kaiyanapp.com/api/";

export const Daily_URL: string = BASE_URL + "v2/feed?num=0";

export const HOT_TAB_URL: string = BASE_URL + "v4/rankList";

export const FOLLOW_URL: string = BASE_URL + "v4/tabs/follow";

export const CATEGORY_URL: string = BASE_URL + "v4/categories";

export const TOPIC_URL: string = BASE_URL + "v3/specialTopics";

export const NEWS_URL: string = BASE_URL + "v7/information/list?vc=6030000&deviceModel=Android";

export const RECOMMEND_LIST: string = BASE_URL + "v7/community/tab/rec";

export const RELATED_VIDEO = BASE_URL + "v4/video/related";

export const TOPIC_DETAIL_URL = BASE_URL + "v3/lightTopics/internal/"

export const INTELLIGENT_CHAT_URL = 'https://spark-api-open.xf-yun.com/v2/chat/completions'

export const INTELLIGENT_IMAGE_SYNTHESIS_URL =
  'https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis'

export const INTELLIGENT_IMAGE_TASK_QUERY_URL = 'https://dashscope.aliyuncs.com/api/v1/tasks/{task_id}';


