const BASE_URL: string = "http://baobab.kaiyanapp.com/api/";

export const Daily_URL: string = BASE_URL + "v2/feed?num=0";

export const HOT_TAB_URL: string = BASE_URL + "v4/rankList";

export const FOLLOW_URL: string = BASE_URL + "v4/tabs/follow";

export const CATEGORY_URL: string = BASE_URL + "v4/categories";

export const TOPIC_URL: string = BASE_URL + "v3/specialTopics";

export const NEWS_URL: string = BASE_URL + "v7/information/list?vc=6030000&deviceModel=Android";

export const RECOMMEND_LIST: string = BASE_URL + "v7/community/tab/rec";

export const RELATED_VIDEO = BASE_URL + "v4/video/related";

